Threading
=========

Actor uses ruby threads (see https://ruby-doc.org/core-2.5.0/Thread.html) to host individual actor instances. This brings some benefits as well as some limitations. Specifically, threads allow an approach to IO to which users of the ruby standard library are already familiar. Unlike other concurrency libraries for ruby, actors may "block," meaning that IO operations can be allowed to pause execution until the underlying operating system indicates the operation is finished. The advantage of this is that programmers can both write and make use of code that is not specifically tied to a particular concurrency library, such as https://github.com/eventmachine/eventmachine[EventMachine] or https://github.com/celluloid/celluloid[Celluloid]. The chief disadvantage of threading is that an operating system process is allocated for each thread. Therefore, per-thread performance may diminish when hundreds or thousands of threads are running in parallel. By contrast, https://ruby-doc.org/core-2.5.0/Fiber.html[Fibers] possess a much smaller resource footprint, and are much more suitable for fine-grained concurrency where thousands of individual processes may run simultaneously, but require non-blocking IO to be employed exclusively.

Threads may terminated at any time. Whenever an actor's thread is terminated, the actor may be placed in a new thread and resume processing messages. In such cases, the actor will begin by handling whatever message was being handled when the previous thread terminated. Therefore, actor message handlers must be idempotent.
