require 'ostruct'

require 'test_bench/controls/binding'
require 'test_bench/controls/clock/elapsed'
require 'test_bench/controls/clock/reference'
require 'test_bench/controls/dir_substitute'
require 'test_bench/controls/executor/substitute'
require 'test_bench/controls/expand_path'
require 'test_bench/controls/error'
require 'test_bench/controls/fixture'
require 'test_bench/controls/kernel_substitute'
require 'test_bench/controls/output'
require 'test_bench/controls/path'
require 'test_bench/controls/result'
require 'test_bench/controls/telemetry'
require 'test_bench/controls/test_script'
